// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// pio_rx //
// ------ //

#define pio_rx_wrap_target 0
#define pio_rx_wrap 4
#define pio_rx_pio_version 0

static const uint16_t pio_rx_program_instructions[] = {
    //     .wrap_target
    0x2020, //  0: wait   0 pin, 0
    0xea27, //  1: set    x, 7    [10]
    0x4001, //  2: in     pins, 1
    0x0642, //  3: jmp    x--, 2  [6]
    0x8020, //  4: push   block
    //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_rx_program = {
    .instructions = pio_rx_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = pio_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pio_rx_program_get_default_config(uint offset)
{
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_rx_wrap_target, offset + pio_rx_wrap);
    return c;
}

static inline void pio_rx_program_init(PIO pio, uint sm, uint offset, uint pin)
{
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, false);
    pio_gpio_init(pio, pin);
    gpio_pull_up(pin);
    pio_sm_config c = pio_rx_program_get_default_config(offset);
    sm_config_set_in_pins(&c, pin); // for WAIT, IN
    sm_config_set_jmp_pin(&c, pin); // for WAIT
    // Shift right, no autopush; push occurs explicitly in program
    sm_config_set_in_shift(&c, true, false, 32);
    pio_sm_init(pio, sm, offset, &c);
}

#endif
